package contsauser

import (
	"context"
	"fmt"
	"net/http"
	isauser "property/framework/interface/sa/sa_user"
	"property/framework/models"
	"property/framework/pkg/app"
	"property/framework/pkg/logging"
	util "property/framework/pkg/utils"
	"strconv"

	_ "property/framework/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/astaxie/beego/validation"
	"github.com/labstack/echo/v4"
	"github.com/sirupsen/logrus"
	echoSwagger "github.com/swaggo/echo-swagger"
	"gopkg.in/go-playground/validator.v9"
)

// ContSaUser :
type ContSaUser struct {
	useSaUser isauser.Usercase
}

// NewContSaUser :
func NewContSaUser(e *echo.Echo, useSaUser isauser.Usercase) {
	controller := &ContSaUser{
		useSaUser: useSaUser,
	}
	/*
		url := echoSwagger.URL("http://localhost:1323/swagger/doc.json") //The url pointing to API definition
	*/
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.GET("/user/:id", controller.GetBySaUser)
	e.GET("/user", controller.GetAllSaUser)
	e.POST("/user", controller.CreateSaUser)
	e.PUT("/user/:id", controller.UpdateSaUser)
	e.DELETE("/user/:id", controller.DeleteSaUser)
}

// GetBySaUser :
// @Summary Get SaUser
// @Tags SaUser
// @Produce  json
// @Param id path int true "ID"
// @Success 200 {object} app.ResponseModel
// @Router /user/{id} [get]
func (u *ContSaUser) GetBySaUser(e echo.Context) error {
	ctx := e.Request().Context()
	if ctx == nil {
		ctx = context.Background()
	}

	var (
		logger = logging.Logger{E: e}
		appE   = app.Res{R: e}
		id     = util.StrTo(e.Param("id")).MustInt()
		valid  validation.Validation
	)

	valid.Min(id, 1, "id").Message("ID must be greater than 0")
	logger.Info(id)
	if valid.HasErrors() {
		// logger.Error(appE.Response(http.StatusBadRequest, app.MarkErrors(valid.Errors), nil))
		return appE.Response(http.StatusBadRequest, app.MarkErrors(valid.Errors), nil)
	}

	DataUser, err := u.useSaUser.GetBySaUser(ctx, int16(id))
	if err != nil {
		// logger.Error(appE.Response(http.StatusInternalServerError, fmt.Sprintf("%v", err), nil))
		return appE.Response(http.StatusInternalServerError, fmt.Sprintf("%v", err), nil)
		// return e.JSON(http.StatusInternalServerError, err.Error())
	}
	// logger.Info(appE.Response(http.StatusOK, "Ok", DataUser))
	// return e.JSON(http.StatusOK, DataUser)
	return appE.Response(http.StatusOK, "OK", DataUser)
}

// GetAllSaUser :
func (u *ContSaUser) GetAllSaUser(e echo.Context) error {
	ctx := e.Request().Context()
	if ctx == nil {
		ctx = context.Background()
	}

	ListDataUser, err := u.useSaUser.GetAllSaUser(ctx)
	if err != nil {
		return e.JSON(http.StatusBadRequest, err.Error())
	}

	return e.JSON(http.StatusOK, ListDataUser)
}

// CreateSaUser :
func (u *ContSaUser) CreateSaUser(e echo.Context) error {
	var user models.SaUser
	err := e.Bind(&user)
	if err != nil {
		return e.JSON(http.StatusUnprocessableEntity, err.Error())
	}

	if ok, err := isRequestValid(&user); !ok {
		return e.JSON(http.StatusBadRequest, err.Error())
	}

	ctx := e.Request().Context()
	if ctx == nil {
		ctx = context.Background()
	}

	err = u.useSaUser.CreateSaUser(ctx, &user)
	if err != nil {
		return e.JSON(getStatusCode(err), err.Error())
	}
	return e.JSON(http.StatusCreated, user)
}

// UpdateSaUser :
func (u *ContSaUser) UpdateSaUser(e echo.Context) error {
	var user models.SaUser
	err := e.Bind(&user)
	if err != nil {
		return e.JSON(http.StatusUnprocessableEntity, err.Error())
	}
	userID, err := strconv.Atoi(e.Param("id"))
	if err != nil {
		return e.JSON(http.StatusNotFound, models.ErrNotFound.Error())
	}
	user.UserID = int16(userID)

	if ok, err := isRequestValid(&user); !ok {
		return e.JSON(http.StatusBadRequest, err.Error())
	}

	ctx := e.Request().Context()
	if ctx == nil {
		ctx = context.Background()
	}

	err = u.useSaUser.UpdateSaUser(ctx, &user)
	if err != nil {
		return e.JSON(getStatusCode(err), err.Error())
	}
	return e.JSON(http.StatusCreated, user)
}

// DeleteSaUser :
func (u *ContSaUser) DeleteSaUser(e echo.Context) error {
	ctx := e.Request().Context()
	if ctx == nil {
		ctx = context.Background()
	}
	userID, err := strconv.Atoi(e.Param("id"))
	if err != nil {
		return e.JSON(http.StatusNotFound, models.ErrNotFound.Error())
	}
	err = u.useSaUser.DeleteSaUser(ctx, int16(userID))
	if err != nil {
		return e.JSON(getStatusCode(err), err.Error())
	}
	return e.NoContent(http.StatusNoContent)
}

// HealthCheck :
func (u *ContSaUser) HealthCheck(c echo.Context) error {
	return c.JSON(http.StatusOK, "success")
}

// isRequestValid
func isRequestValid(m *models.SaUser) (bool, error) {
	validate := validator.New()
	err := validate.Struct(m)
	if err != nil {
		return false, err
	}
	return true, nil
}

// getStatusCode
func getStatusCode(err error) int {
	if err == nil {
		return http.StatusOK
	}
	logrus.Error(err)
	switch err {
	case models.ErrInternalServerError:
		return http.StatusInternalServerError
	case models.ErrNotFound:
		return http.StatusNotFound
	case models.ErrConflict:
		return http.StatusConflict
	default:
		return http.StatusInternalServerError
	}
}
