definitions:
  app.ResponseModel:
    properties:
      data:
        type: object
      msg:
        description: Code int         `json:"code"`
        type: string
    type: object
  contauth.LoginForm:
    properties:
      p:
        type: string
      u:
        type: string
    type: object
  contauth.RegisterForm:
    properties:
      address:
        type: string
      client_name:
        type: string
      client_type:
        type: string
      contact_person:
        type: string
      created_by:
        type: string
      email_addr:
        type: string
      expiry_date:
        type: string
      joining_date:
        type: string
      post_cd:
        type: string
      start_billing_date:
        type: string
      telephone_no:
        type: string
    type: object
  contsarole.AddRoleForm:
    properties:
      created_by:
        type: string
      descs:
        type: string
      num:
        type: number
    type: object
  contsarole.EditRoleForm:
    properties:
      Updated_by:
        type: string
      descs:
        type: string
    type: object
  models.AddUserForm:
    properties:
      company_id:
        type: integer
      created_by:
        type: string
      data_permission:
        type: string
      email_addr:
        type: string
      handphone_no:
        type: string
      level_no:
        type: integer
      name:
        type: string
      picture_url:
        type: string
      project_id:
        type: integer
      role_id:
        type: string
      user_name:
        type: string
      user_status:
        type: integer
    type: object
  models.EditUserForm:
    properties:
      company_id:
        type: integer
      data_permission:
        type: string
      email_addr:
        type: string
      handphone_no:
        type: string
      level_no:
        type: integer
      name:
        type: string
      picture_url:
        type: string
      project_id:
        type: integer
      role_id:
        type: string
      updated_by:
        type: string
      user_name:
        type: string
      user_status:
        type: integer
    type: object
  models.ResponseModelList:
    properties:
      data:
        type: object
      last_page:
        type: integer
      msg:
        type: string
      page:
        type: integer
      total:
        type: integer
    type: object
info:
  contact:
    email: nuryantofattih@gmail.com
    name: Nuryanto
    url: https://www.linkedin.com/in/nuryanto-1b2721156/
  description: Backend REST API for golang starter
  license: {}
  title: Starter
  version: "1.0"
paths:
  /api/auth/login:
    post:
      parameters:
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/contauth.LoginForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: Login
      tags:
      - Auth
  /api/auth/register:
    post:
      parameters:
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/contauth.RegisterForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: Add Client
      tags:
      - Auth
  /api/role:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      summary: GetList SaRole
      tags:
      - Role
    post:
      parameters:
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/contsarole.AddRoleForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: Add Role
      tags:
      - Role
  /api/role/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: Delete role
      tags:
      - Role
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: GetById SaRole
      tags:
      - Role
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/contsarole.EditRoleForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      summary: Update Role
      tags:
      - Role
  /api/user:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: GetList SaUser
      tags:
      - User
    get:
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      security:
      - ApiKeyAuth: []
      summary: GetList SaUser
      tags:
      - User
    post:
      parameters:
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.AddUserForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Add User
      tags:
      - User
  /api/user/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: GetById SaUser
      tags:
      - User
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.EditUserForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - User
  /api/user/permission:
    get:
      parameters:
      - description: ClientID
        in: query
        name: client_id
        required: true
        type: string
      - description: UserID
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Get string Array Permission User
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
